site_name: Xopt
repo_url: https://github.com/ChristopherMayes/Xopt
repo_name: ChristopherMayes/Xopt

nav:
    - Home: index.md
    - Installation: installation.md
    - Algorithms: algorithms.md
    - Examples:
        - Basics:
            - examples/basic/xopt_basic.ipynb
            - examples/basic/xopt_parallel.ipynb
            - examples/basic/xopt_vocs.ipynb
        - Bayesian:
            - Bayesian Exploration:
                - Bayesian Exploration: examples/bayes_exp/bayesian_exploration.ipynb
                - Bayesian Exploration from yaml: examples/bayes_exp/bayesian_exploration_from_yaml.ipynb
            - Single Objective Bayesian Optimization:
                - Bayesian optimization tutorial: examples/single_objective_bayes_opt/bo_tutorial.ipynb
                - Upper confidence bound: examples/single_objective_bayes_opt/upper_confidence_bound.ipynb
                - Expected improvement: examples/single_objective_bayes_opt/expected_improvement_rosenbrock.ipynb
                - Custom GP models: examples/single_objective_bayes_opt/custom_model.ipynb
                - Trust region: examples/single_objective_bayes_opt/turbo_tutorial.ipynb
                - Multi-Fidelity: examples/single_objective_bayes_opt/multi_fidelity_simple.ipynb
                - Time dependent upper confidence bound: examples/single_objective_bayes_opt/time_dependent_bo.ipynb
            - Multi-Objective Bayesian Optimization:
                - Expected hypervolume improvement: examples/multi_objective_bayes_opt/mobo.ipynb
                - Multi-fidelity expected hypervolume improvement: examples/multi_objective_bayes_opt/multi_fidelity_mobo.ipynb
                - Multi-generation gaussian process optimization: examples/multi_objective_bayes_opt/mggpo.ipynb
        - Evolutionary:
            - CNSGA: examples/cnsga/cnsga_tnk.ipynb
        - SciPy:
            - Nelder-Mead: examples/scipy/neldermead.ipynb
        - Other:
            - Extremum seeking: examples/es/extremum_seeking.ipynb
            - RCDS: examples/rcds/rcds.ipynb


    - API:
      - Xopt: api/xopt.md
      - Vocs: api/vocs.md
      - Evaluator: api/evaluator.md
      - Generators:
          - Base generator class: api/generators.md
          - Bayesian generators: api/generators/bayesian.md
          - Genetic generators: api/generators/genetic.md
          - SciPy generators: api/generators/scipy.md

theme:
  icon:
    repo: fontawesome/brands/github
  name: material

  custom_dir: overrides
  features:
    - navigation.top
    - navigation.tabs
    - navigation.indexes
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ChristopherMayes/Xopt
      name: Xopt

extra_css:
  - stylesheets/extra.css

plugins:
    - search

    - mkdocs-jupyter:
        include_source: True

    - mkdocstrings:
        default_handler: python
        handlers:
          python:
            selection:
              docstring_style: "numpy"
              inherited_members: false
              filters:
                - "!^_"  # exclude all members starting with _
                - "^__init__$"  # but always include __init__ modules and methods
            rendering:
              show_source: true
              show_root_heading: true






