name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
        run:
          shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge
          activate-environment: xopt-dev
          environment-file: environment.yml
          
      - name: flake8
        shell: bash -l {0}
        run: |
          flake8 .

      - name: Install Xopt
        shell: bash -l {0}
        run: |
          pip install --no-dependencies .

      - name: Run Tests
        shell: bash -l {0}
        run: |
          python run_tests.py

      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user          

      - name: Build a source tarball
        shell: bash -l {0}
        run: >-
          python -m
          build
          --sdist
          --outdir dist/
          .
