name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
        run:
          shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: true
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge

      - name: Create environment
        shell: bash -l {0}
        run: |
          pip install -r requirements.txt
          pip install -r test-requirements.txt
          
      - name: flake8
        run: |
          flake8 .

      - name: Install Xopt
        shell: bash -l {0}
        run: |
          pip install --no-dependencies .

      - name: Run Tests
        shell: bash -l {0}
        run: |
          python run_tests.py
